# Generated by Django 5.0.6 on 2024-08-14 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("page_name", models.CharField(max_length=100)),
                ("page_cat", models.CharField(max_length=100)),
                ("page_publish_date", models.DateField(max_length=100)),
            ],
        ),
    ]
